feat: add diagnostic filtering
jose-elias-alvarez/nvim-lsp-ts-utils pull request #56
Opened 2021-08-15 09:18 UTC by nawordar

Closes #55.

So far, function `require("nvim-lsp-ts-utils").setup_client` was meant only for fixing ranges, but now it will also wrap `textDocument/publishDiagnostics` handler. My suggestion is to always run `setup_client` inside `require("nvim-lsp-ts-utils").setup` and enable fixing ranges using an option (is it even still needed?).

2021-08-15 15:17 UTC, jose-elias-alvarez commented
Thanks for putting this together! I quickly scanned it and it looks good (I especially appreciate the test coverage), but I'll have time to fully review it and test it out locally tomorrow. A couple of quick impressions:

1. I think it would be nice to allow users to set the severities they want to ignore as strings (e.g. `"hint"` instead of `4`), since it's not immediately obvious what the numbers correspond to without referring to the LSP documentation. 
2. Could we mention the option in the readme?

2021-08-16 07:58 UTC, nawordar commented
What about having an enum-like table of severities? If so, what are your naming conventions here?

```lua
local ts_utils = require("nvim-lsp-ts-utils")
print(ts_utils.severity.hint) -- 4
```

2021-08-16 15:59 UTC, jose-elias-alvarez requested changes

2021-08-16 15:59 UTC, jose-elias-alvarez commented on lua/nvim-lsp-ts-utils/client.lua
> +    local forbidden_severities = o.get().filter_out_diagnostics_by_severity
Could we rename these variables to match the names of the options? I had a moment of confusion testing this out.

2021-08-16 15:59 UTC, jose-elias-alvarez commented on lua/nvim-lsp-ts-utils/client.lua
> +    return vim.lsp.diagnostic.on_publish_diagnostics(err, method, result, client_id, buf_nr, config)
We should use `lsp.handlers["textDocument/publishDiagnostics"]` to respect options users have set with `vim.lsp.with` (e.g. disabling virtual text).

2021-08-16 16:00 UTC, jose-elias-alvarez commented
I'm not opposed to a table of severities, but what's the advantage of having a dedicated variable vs. allowing strings and converting them with a simple map like this?

```lua
local severities = {
    ["error"] = 1,
    ["warning"] = 2,
    -- etc
}
```

For the tests: I think the first test failure is because `diagnostics_result` is getting mutated in the first test. This diff solves it on my end:

```diff
diff --git a/test/spec/client_spec.lua b/test/spec/client_spec.lua
index 9ebb6a2..9b1ca3e 100644
--- a/test/spec/client_spec.lua
+++ b/test/spec/client_spec.lua
@@ -97,14 +97,18 @@ describe("client", function()
         end)

         describe("diagnostics_handler", function()
-            local diagnostics_result = {
-                diagnostics = {
-                    { source = "eslint", severity = 4, code = 80001 },
-                    { source = "typescript", severity = 1, code = 80001 },
-                    { source = "typescript", severity = 3, code = 80001 },
-                    { source = "typescript", severity = 4, code = 80000 },
-                },
-            }
+            local diagnostics_result
+            before_each(function()
+                diagnostics_result = {
+                    diagnostics = {
+                        { source = "eslint", severity = 4, code = 80001 },
+                        { source = "typescript", severity = 1, code = 80001 },
+                        { source = "typescript", severity = 3, code = 80001 },
+                        { source = "typescript", severity = 4, code = 80000 },
+                    },
+                }
+            end)

             it("should filter out hints", function()
                 o.get.returns({
```

I wouldn't worry too much about the import all test, since it's flaky, but you're correct that filtering out errors does affect `:TSLspImportAll`. I don't know if users will really want to filter out errors, so if you think it's okay, I think we can just add a warning in the documentation about the interaction and deal with it later if it comes up.

2021-08-16 16:49 UTC, nawordar commented
> I'm not opposed to a table of severities, but what's the advantage of having a dedicated variable vs. allowing strings and converting them with a simple map like this?
> 
> ```lua
> local severities = {
>     ["error"] = 1,
>     ["warning"] = 2,
>     -- etc
> }
> ```

This is a nice idea. I think I will put `severities` in `utils` if it will ever be needed in other files.

2021-08-17 06:27 UTC, jose-elias-alvarez commented
LGTM, thanks for working on this! 

I have to think about how to make testing in general more reliable, since Plenary / Luassert weren't really built to handle cases like this, but as long as it actually works it should be fine for now.

2021-08-17 06:27 UTC, merged